### ISSUE TITLE
Illegal instruction on shell script start

### ISSUE THREAD

**Issue by stomydent** [essen/chat_tutorial#3]
**$ ./start.sh**
{"init terminating in do_boot",{undef,[{websocket,start,[],[]},{init,start_em,1,[{file,"init.erl"},{line,1085}]},{init,do_boot,3,[{file,"init.erl"},{line,793}]}]}}
init terminating in do_boot ({undef,[{websocket,start,[],[]},{init,start_em,1,[{_},{_}]},{init,do_boot,3,[{_},{_}]}]})

Crash dump is being written to: erl_crash.dump..../start.sh: line 3:  6720 Illegal instruction     erl -pa ebin deps/*/ebin -boot start_sasl -s websocket -eval "io:format(\"Point your browser at http://localhost:8080/ to use a simple websocket client~n\")."

erl_crash.dump is empty. Using Erlang 9.3 on Windows x64. 
Thanks!

**Comment by essen** [comment]
It's very old and very unmaintained. Please use https://github.com/ninenines/cowboy/tree/master/examples/websocket
